### ISSUE TITLE
Negative values in "outflow" field

### ISSUE THREAD

**Issue by ohthehugemanatee** [cjhowald/ynab-csv#13]
This only cropped up recently, and I don't know if it's a change in my bank's CSV, the converter, or YNAB. In any case, i have a CSV that uses negative values in its "outflow" field. Those negative values are loyally entered into the YNAB CSV, and YNAB then imports them... as inflows.

There is probably an occasional use case for a negative value in "outflow" meaning an inflow, but that would be an isolated transaction. Add handling to detect if all the outflow values are negative, and multiply by -1.

**Comment by cjhowald** [comment]
I recently refactored the number handling a bit to restore a use case I accidentally dropped when I initially forked and refactored this repo: If inflow and outflow are set to the same column, it splits them based on sign (i.e. all the positive values go to inflow and the negative to outflow). This is useful for CSV exports that use a single column for inflows and outflows.

However, if inflow and outflow map from different columns, then I think it is reasonable to always take the absolute value. I believe this will resolve this issue.
